### ISSUE TITLE
0.664测评

### ISSUE THREAD

**Issue by mahengrui1** [piiiiq/Black#1]
试了试，有特色

0.664

1 自带生成名字
2 支持全屏护眼写作
3 支持自定义多个文档的上下级关系
4 支持多种字体

bug

1 使用替换功能时，一直点替换，会原地蹦字。
我来了
我 替换 你 一直点
你你你你来了

对2个字进行“前一个”查找无效

2 全屏写作时无法检测分辨率，宽屏电脑的鼠标够不到右侧的进度条，需要在首选项-写作试图 里调宽

3 偶尔有复制粘贴不全的情况（复制整本《斗破苍穹》（500万字），保存重开后在160万字断掉，无法复制该错误）

与NotePad++比较

0 采用Apache许可证 （更优）

Notepad++：采用GPL许可证

1 可以自动完成和补全经常输入的中文词汇（前提是定义了关键词列表）
Notepad++：可以自动完成和补全所有中文词汇，关键词列表可以随意插入、自动探测、计数（更优）

2 一般100MB到200MB内存
Notepad++：5MB到50MB（更优）

3 启动速度，以《斗破苍穹》为例，1分钟
Notepad++：0.5秒（更优）

4 快速翻页、搜索：流畅（更优）
Notepad++：达到《斗破苍穹》程度后，翻页和搜索”载入功能“会有10秒左右卡顿，”使用功能“流畅，但“故意测试功能”会一直卡顿

5 搜索引擎重名严重
Notepad++：置顶（更优）

**Comment by piiiiq** [comment]
notepad++ 以下简称npp
blackDraft 以下简称bd

首先npp针对的是程序代码编辑，bd针对的是中文纯文本自然语言写作，两者的应用场景不同。其次，这两个程序的成熟度也完全不同，npp已经是非常成熟的软件，bd却开发不久，还有很多bug。

对于检索功能，bd的检索功能只提供了基本的功能，这个无需讨论，条件允许的话，开发者会持续改进这个功能和bd的其他功能；

关于内存占用以及性能，两者没有可比性，npp使用c++写的，bd是用java写的，c++是上一代编程语言，针对的是高性能应用场景，或者是老旧硬件应用场景，能够最大化缩减硬件资源占用，但是c++程序的编写与维护都很困难，增加了开发者的负担；而java语言是针对现代计算机硬件的编程语言，注重点不在减少硬件资源占用上，而是在快速开发及部署上，java程序是运行在虚拟机（jvm）之上的（为了跨平台特性，一次编写就可以运行在几乎所有的系统与硬件平台上），因为使用了虚拟机，所以就算java程序什么也不做也会占用二三十兆内存，再者，java程序的内存是由虚拟机自动管理的，编程者不能显式的释放内存，很多时候java程序（虚拟机）即便不再使用某些资源也会将其缓存在内存里，以便加快以后的调用，因此就内存占用而言，无论怎么优化，java程序也不可能达到C++程序那样的级别。

对于自动完成功能，鉴于bd是针对自然语言（中文）写作用的工具，所以这里只讨论针对自然语言（中文）的自动完成功能，不讨论针对程序源代码的。以前没怎么用过npp，看到你对npp的自动完成的描述后觉得npp的自动完成似乎很不错，所以特意从github下载了最新版的npp（v7.8.9）试了一下。使用后发现npp的自动完成对于中文自然语言写作用处不大（就我自己的写作需求而言），基于我的使用来看（如有错误或遗漏请回复指正），首先npp的自动完成是基于单文档的，只能自动检索和提示同一个文档内的词汇，这样对要编辑多个、却同属于同一个主题（例如同一部小说）的文档无法自动完成，除非在每个文档内将需要自动完成的词汇再写一遍；其次就是自动完成的准确性的问题，npp是通过一些符号来切分文档内的字符并决定其是否出现在自动完成列表内的（例如换行符、英文、标点之类的），这样绝大多数时候都不准确，因为中文词汇不是像英文那样用空格来切分的，所以基本上，一个程序如果没有语义分析和自动分词系统，只通过一些符号想从一段中文中切分出写作者想要的词汇是不可能的，结果还不如让写作者定义关键词来的准确。
如果想要不定义关键词就可以自动完成中文自然语言词汇，就必须使用分词系统，bd实际上有过这个计划，但由于分词系统加载后会占用很多内存（一百兆以上），所以放弃了这个计划，后续版本也许会开启此功能。
另bd最新版本已经是0.6757,修复了一些bug，提供了一些有意思的新功能，例如能够自动下载和部署增量更新（增量更新一般在1MB以内）功能，免去每次想用新版本时还得下载完整包的麻烦，而且现在写作试图能够使用Bing每日图片作为背景图片，有关最新版的更多信息请查看releases页面：https://github.com/piiiiq/BlackDraft/releases

**Comment by piiiiq** [comment]
notepad++ 以下简称npp
blackDraft 以下简称bd

首先npp针对的是程序代码编辑，bd针对的是中文纯文本自然语言写作，两者的应用场景不同。其次，这两个程序的成熟度也完全不同，npp已经是非常成熟的软件，bd却开发不久，还有很多bug。

对于检索功能，bd的检索功能只提供了基本的功能，这个无需讨论，条件允许的话，开发者会持续改进这个功能和bd的其他功能；

关于内存占用以及性能，两者没有可比性，npp使用c++写的，bd是用java写的，c++是上一代编程语言，针对的是高性能应用场景，或者是老旧硬件应用场景，能够最大化缩减硬件资源占用，但是c++程序的编写与维护都很困难，增加了开发者的负担；而java语言是针对现代计算机硬件的编程语言，注重点不在减少硬件资源占用上，而是在快速开发及部署上，java程序是运行在虚拟机（jvm）之上的（为了跨平台特性，一次编写就可以运行在几乎所有的系统与硬件平台上），因为使用了虚拟机，所以就算java程序什么也不做也会占用二三十兆内存，再者，java程序的内存是由虚拟机自动管理的，编程者不能显式的释放内存，很多时候java程序（虚拟机）即便不再使用某些资源也会将其缓存在内存里，以便加快以后的调用，因此就内存占用而言，无论怎么优化，java程序也不可能达到C++程序那样的级别。

对于自动完成功能，鉴于bd是针对自然语言（中文）写作用的工具，所以这里只讨论针对自然语言（中文）的自动完成功能，不讨论针对程序源代码的。以前没怎么用过npp，看到你对npp的自动完成的描述后觉得npp的自动完成似乎很不错，所以特意从github下载了最新版的npp（v7.8.9）试了一下。使用后发现npp的自动完成对于中文自然语言写作用处不大（就我自己的写作需求而言），基于我的使用来看（如有错误或遗漏请回复指正），首先npp的自动完成是基于单文档的，只能自动检索和提示同一个文档内的词汇，这样对要编辑多个、却同属于同一个主题（例如同一部小说）的文档无法自动完成，除非在每个文档内将需要自动完成的词汇再写一遍；其次就是自动完成的准确性的问题，npp是通过一些符号来切分文档内的字符并决定其是否出现在自动完成列表内的（例如换行符、英文、标点之类的），这样绝大多数时候都不准确，因为中文词汇不是像英文那样用空格来切分的，所以基本上，一个程序如果没有语义分析和自动分词系统，只通过一些符号想从一段中文中切分出写作者想要的词汇是不可能的，结果还不如让写作者定义关键词来的准确。

如果想要不定义关键词就可以自动完成中文自然语言词汇，就必须使用分词系统，bd实际上有过这个计划，但由于分词系统加载后会占用很多内存（一百兆以上），所以放弃了这个计划，后续版本也许会开启此功能。

另bd最新版本已经是0.6757,修复了一些bug，提供了一些有意思的新功能，例如能够自动下载和部署增量更新（增量更新一般在1MB以内），免去每次想用新版本时还得下载完整包的麻烦，而且现在写作视图能够使用Bing每日图片作为背景图片，有关最新版的更多信息请查看releases页面：https://github.com/piiiiq/BlackDraft/releases

**Comment by piiiiq** [comment]
notepad++ 以下简称npp
blackDraft 以下简称bd

首先npp针对的是程序代码编辑，bd针对的是中文纯文本自然语言写作，两者的应用场景不同。其次，这两个程序的成熟度也完全不同，npp已经是非常成熟的软件，bd却开发不久，还有很多bug。

对于检索功能，bd的检索功能只提供了基本的功能，这个无需讨论，条件允许的话，开发者会持续改进这个功能和bd的其他功能；

关于内存占用以及性能，两者没有可比性，npp使用c++写的，bd是用java写的，c++是上一代编程语言，针对的是高性能应用场景，或者是老旧硬件应用场景，能够最大化缩减硬件资源占用，但是c++程序的编写与维护都很困难，增加了开发者的负担；而java语言是针对现代计算机硬件的编程语言，注重点不在减少硬件资源占用上，而是在快速开发及部署上，java程序是运行在虚拟机（jvm）之上的（为了跨平台特性，一次编写就可以运行在几乎所有的系统与硬件平台上），因为使用了虚拟机，所以就算java程序什么也不做也会占用二三十兆内存，再者，java程序的内存是由虚拟机自动管理的，编程者不能显式的释放内存，很多时候java程序（虚拟机）即便不再使用某些资源也会将其缓存在内存里，以便加快以后的调用，因此就内存占用而言，无论怎么优化，java程序也不可能达到C++程序那样的级别。

对于自动完成功能，鉴于bd是针对自然语言（中文）写作用的工具，所以这里只讨论针对自然语言（中文）的自动完成功能，不讨论针对程序源代码的。以前没怎么用过npp，看到你对npp的自动完成的描述后觉得npp的自动完成似乎很不错，所以特意从github下载了最新版的npp（v7.8.9）试了一下。使用后发现npp的自动完成对于中文自然语言写作用处不大（就我自己的写作需求而言），基于我的使用来看（如有错误或遗漏请回复指正），首先npp的自动完成是基于单文档的，只能自动检索和提示同一个文档内的词汇，这样对要编辑多个、却同属于同一个主题（例如同一部小说）的文档无法自动完成，除非在每个文档内将需要自动完成的词汇再写一遍；其次就是自动完成的准确性的问题，npp是通过一些符号来切分文档内的字符并决定其是否出现在自动完成列表内的（例如换行符、英文、标点之类的），这样绝大多数时候都不准确，因为中文词汇不是像英文那样用空格来切分的，所以基本上，一个程序如果没有语义分析和自动分词系统，只通过一些符号想从一段中文中切分出写作者想要的词汇是不可能的，结果还不如让写作者定义关键词来的准确。

如果想要不定义关键词就可以自动完成中文自然语言词汇，就必须使用分词系统，没有分词系统切分出来的词汇就不会准确，npp并没有中文分词系统，npp的自动完成对于程序代码还行，对于中文自然语言基本上没用。bd实际上有过使用分词系统的计划，但由于分词系统加载后会占用很多内存（一百兆以上），所以放弃了这个计划，后续版本也许会开启此功能。

至于文档加载速度，两者也没有可比性，npp的编辑器是纯文本编辑器，bd的编辑器是富文本编辑器（虽然bd没有启用富文本编辑功能，但不排除以后会启用），这两种编辑器之间的功能差距就导致了加载速度的不同。

另bd最新版本已经是0.6757,修复了一些bug，提供了一些有意思的新功能，例如能够自动下载和部署增量更新（增量更新一般在1MB以内），免去每次想用新版本时还得下载完整包的麻烦，而且现在写作视图能够使用Bing每日图片作为背景图片，有关最新版的更多信息请查看releases页面：https://github.com/piiiiq/BlackDraft/releases

**Comment by piiiiq** [comment]
使用的Qtjambi 4.8可能存在内存泄露问题，有空将底层Qtjambi库升级到5.15试试内存问题是否已被修复

**Comment by mahengrui1** [comment]
> 
> 
> 使用的Qtjambi 4.8可能存在内存泄露问题，有空将底层Qtjambi库升级到5.15试试内存问题是否已被修复

我的电脑没有装java
