### ISSUE TITLE
最新版的完全体安装包文件好像没了

### ISSUE THREAD

**Issue by ligenxun** [piiiiq/Black#2]
最新版本的安装包，点击下载后，会跳转到剪切板，然后剪切板内没有文件，只有文本内容（包括点击切换文件，也没有可下载文件）

**Comment by ligenxun** [comment]
https://netcut.cn/p/e1903489fef16c63 这个里面的完整版文件，好像没了 @piiiiq 大佬麻烦给看下

**Comment by piiiiq** [comment]
收到反馈，会尽快修复

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by piiiiq** [comment]
已经重新上传压缩包到原云剪切板，链接未变。

**Comment by ligenxun** [comment]
> 已经重新上传压缩包到原云剪切板，链接未变。

好的，非常感谢！！

**Comment by ligenxun** [comment]
无法运行，换了两台电脑，一台是Windows10 64位，一台Windows7 64位，都无法运行。点击图标后无反应，关闭了杀毒软件+管理员模式运行，也无反应

**Comment by piiiiq** [comment]
将程序根目录下log文件夹内的文本文件内容贴上来。

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by piiiiq** [comment]
我这边重新上传了0.6782的完整包，上次你下载的是0.6781的完整包。我这边测试两个版本的完整包都能启动。你可以从原链接重新下载一次再试，如果依旧无法启动，请将程序根目录下的Logs文件夹内的log.txt文件的内容贴上来。

**Comment by ligenxun** [comment]
> 我这边重新上传了0.6782的完整包，上次你下载的是0.6781的完整包。我这边测试两个版本的完整包都能启动。你可以从原链接重新下载一次再试，如果依旧无法启动，请将程序根目录下的Logs文件夹内的log.txt文件的内容贴上来。

好的好的，我马上试下

**Comment by ligenxun** [comment]
还是打不开，我把Logs文件打包上传了，你看下 #

> `java.lang.RuntimeException: Loading library failed, progress so far:
Unpacking .jar file: 'qtjambi-native-win32-mingw-w64-4.8.6.jar'
**_Checking Archive 'jar:file:/D:/MyFile/LiteRuanjian/BlackDraft_x86/bin_/black_lib/qtjambi-native-win32-mingw-w64-4.8.6.jar!_**

**Comment by ligenxun** [comment]
开始部署更新...
更新模块版本：0.31
程序根目录：D:\Apps\Unpack\MyApp\BlackDraft\.
更新包路径：D:\Apps\Unpack\MyApp\BlackDraft\.\update\0.6782.zip
blackDraft启动文件路径：D:\Apps\Unpack\MyApp\BlackDraft\.\BlackDraft.exe
black.jar文件是否存在：true
zip文件：D:\Apps\Unpack\MyApp\BlackDraft\.\update\0.6782.zip
zip文件解压目标目录：D:\Apps\Unpack\MyApp\BlackDraft\.
更新部署完成
blackdraft执行文件目录：D:\Apps\Unpack\MyApp\BlackDraft\.\BlackDraft.exe

**Comment by piiiiq** [comment]
已经修复，是我打包的时候为了缩减压缩包体积而错删掉了关键库文件，在我的机器上那个被删掉的库文件因为已经被缓存到操作系统temp文件夹内，所以我这边测试的时候程序是能够正常启动的。
修正的压缩包已经上传到原链接，再次下载即可。

**Comment by ligenxun** [comment]
> 已经修复，是我打包的时候为了缩减压缩包体积而错删掉了关键库文件，在我的机器上那个被删掉的库文件因为已经被缓存到操作系统temp文件夹内，所以我这边测试的时候程序是能够正常启动的。
> 修正的压缩包已经上传到原链接，再次下载即可。

好的好的，现在可以用了，非常感谢大佬！！
